name: Spirit
version: ${pluginVersion}
author: dan
api-version: "1.16"
description: Spirit Event Logger
main: com.danielraybone.spirit.SpiritPaper
website: "https://github.com/iAverages/Spirit"
softdepend: [ ]
